// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class ipc_status_h extends ipc_status_h$shared {

    ipc_status_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("shmipc_shared"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    private static final int IPC_STATUS_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.IPC_STATUS_OK = 0
     * }
     */
    public static int IPC_STATUS_OK() {
        return IPC_STATUS_OK;
    }
    private static final int IPC_STATUS_EMPTY = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.IPC_STATUS_EMPTY = 1
     * }
     */
    public static int IPC_STATUS_EMPTY() {
        return IPC_STATUS_EMPTY;
    }
    private static final int IPC_STATUS_BUSY = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.IPC_STATUS_BUSY = 2
     * }
     */
    public static int IPC_STATUS_BUSY() {
        return IPC_STATUS_BUSY;
    }
    private static final int IPC_STATUS_TIMEOUT = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.IPC_STATUS_TIMEOUT = 3
     * }
     */
    public static int IPC_STATUS_TIMEOUT() {
        return IPC_STATUS_TIMEOUT;
    }
    private static final int IPC_STATUS_NO_SPACE = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.IPC_STATUS_NO_SPACE = 4
     * }
     */
    public static int IPC_STATUS_NO_SPACE() {
        return IPC_STATUS_NO_SPACE;
    }
    private static final int IPC_STATUS_ERROR = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.IPC_STATUS_ERROR = 5
     * }
     */
    public static int IPC_STATUS_ERROR() {
        return IPC_STATUS_ERROR;
    }
}

