// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     ipc_error_kind_t kind;
 *     ipc_error_code_t code;
 *     const char *message;
 *     union {
 *         struct {
 *             union {
 *                 ipc_error_size_t size;
 *                 ipc_error_capacity_t capacity;
 *             };
 *         } arg;
 *         struct {
 *             int sys_errno;
 *         } sys;
 *         struct {
 *             union {
 *                 ipc_error_cas_t cas;
 *                 uint64_t offset;
 *             };
 *         } internal;
 *     } as;
 * }
 * }
 */
public class ipc_error_t {

    ipc_error_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_INT.withName("kind"),
        ipc_channel_h.C_INT.withName("code"),
        ipc_channel_h.C_POINTER.withName("message"),
        ipc_error_t.as.layout().withName("as")
    ).withName("$anon$59:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt kind$LAYOUT = (OfInt)$LAYOUT.select(groupElement("kind"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ipc_error_kind_t kind
     * }
     */
    public static final OfInt kind$layout() {
        return kind$LAYOUT;
    }

    private static final long kind$OFFSET = $LAYOUT.byteOffset(groupElement("kind"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ipc_error_kind_t kind
     * }
     */
    public static final long kind$offset() {
        return kind$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ipc_error_kind_t kind
     * }
     */
    public static int kind(MemorySegment struct) {
        return struct.get(kind$LAYOUT, kind$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ipc_error_kind_t kind
     * }
     */
    public static void kind(MemorySegment struct, int fieldValue) {
        struct.set(kind$LAYOUT, kind$OFFSET, fieldValue);
    }

    private static final OfInt code$LAYOUT = (OfInt)$LAYOUT.select(groupElement("code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ipc_error_code_t code
     * }
     */
    public static final OfInt code$layout() {
        return code$LAYOUT;
    }

    private static final long code$OFFSET = $LAYOUT.byteOffset(groupElement("code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ipc_error_code_t code
     * }
     */
    public static final long code$offset() {
        return code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ipc_error_code_t code
     * }
     */
    public static int code(MemorySegment struct) {
        return struct.get(code$LAYOUT, code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ipc_error_code_t code
     * }
     */
    public static void code(MemorySegment struct, int fieldValue) {
        struct.set(code$LAYOUT, code$OFFSET, fieldValue);
    }

    private static final AddressLayout message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final AddressLayout message$layout() {
        return message$LAYOUT;
    }

    private static final long message$OFFSET = $LAYOUT.byteOffset(groupElement("message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final long message$offset() {
        return message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static MemorySegment message(MemorySegment struct) {
        return struct.get(message$LAYOUT, message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static void message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(message$LAYOUT, message$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     struct {
     *         union {
     *             ipc_error_size_t size;
     *             ipc_error_capacity_t capacity;
     *         };
     *     } arg;
     *     struct {
     *         int sys_errno;
     *     } sys;
     *     struct {
     *         union {
     *             ipc_error_cas_t cas;
     *             uint64_t offset;
     *         };
     *     } internal;
     * }
     * }
     */
    public static class as {

        as() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            ipc_error_t.as.arg.layout().withName("arg"),
            ipc_error_t.as.sys.layout().withName("sys"),
            ipc_error_t.as.internal.layout().withName("internal")
        ).withName("$anon$64:5");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_size_t size;
         *         ipc_error_capacity_t capacity;
         *     };
         * }
         * }
         */
        public static class arg {

            arg() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                MemoryLayout.unionLayout(
                    ipc_error_size_t.layout().withName("size"),
                    ipc_error_capacity_t.layout().withName("capacity")
                ).withName("$anon$66:13")
            ).withName("$anon$65:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final GroupLayout size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$66:13"), groupElement("size"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * ipc_error_size_t size
             * }
             */
            public static final GroupLayout size$layout() {
                return size$LAYOUT;
            }

            private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$66:13"), groupElement("size"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * ipc_error_size_t size
             * }
             */
            public static final long size$offset() {
                return size$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * ipc_error_size_t size
             * }
             */
            public static MemorySegment size(MemorySegment struct) {
                return struct.asSlice(size$OFFSET, size$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * ipc_error_size_t size
             * }
             */
            public static void size(MemorySegment struct, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, struct, size$OFFSET, size$LAYOUT.byteSize());
            }

            private static final GroupLayout capacity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$66:13"), groupElement("capacity"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * ipc_error_capacity_t capacity
             * }
             */
            public static final GroupLayout capacity$layout() {
                return capacity$LAYOUT;
            }

            private static final long capacity$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$66:13"), groupElement("capacity"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * ipc_error_capacity_t capacity
             * }
             */
            public static final long capacity$offset() {
                return capacity$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * ipc_error_capacity_t capacity
             * }
             */
            public static MemorySegment capacity(MemorySegment struct) {
                return struct.asSlice(capacity$OFFSET, capacity$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * ipc_error_capacity_t capacity
             * }
             */
            public static void capacity(MemorySegment struct, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, struct, capacity$OFFSET, capacity$LAYOUT.byteSize());
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout arg$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("arg"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_size_t size;
         *         ipc_error_capacity_t capacity;
         *     };
         * } arg
         * }
         */
        public static final GroupLayout arg$layout() {
            return arg$LAYOUT;
        }

        private static final long arg$OFFSET = $LAYOUT.byteOffset(groupElement("arg"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_size_t size;
         *         ipc_error_capacity_t capacity;
         *     };
         * } arg
         * }
         */
        public static final long arg$offset() {
            return arg$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_size_t size;
         *         ipc_error_capacity_t capacity;
         *     };
         * } arg
         * }
         */
        public static MemorySegment arg(MemorySegment union) {
            return union.asSlice(arg$OFFSET, arg$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_size_t size;
         *         ipc_error_capacity_t capacity;
         *     };
         * } arg
         * }
         */
        public static void arg(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, arg$OFFSET, arg$LAYOUT.byteSize());
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     int sys_errno;
         * }
         * }
         */
        public static class sys {

            sys() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                ipc_channel_h.C_INT.withName("sys_errno")
            ).withName("$anon$72:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final OfInt sys_errno$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sys_errno"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * int sys_errno
             * }
             */
            public static final OfInt sys_errno$layout() {
                return sys_errno$LAYOUT;
            }

            private static final long sys_errno$OFFSET = $LAYOUT.byteOffset(groupElement("sys_errno"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * int sys_errno
             * }
             */
            public static final long sys_errno$offset() {
                return sys_errno$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * int sys_errno
             * }
             */
            public static int sys_errno(MemorySegment struct) {
                return struct.get(sys_errno$LAYOUT, sys_errno$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * int sys_errno
             * }
             */
            public static void sys_errno(MemorySegment struct, int fieldValue) {
                struct.set(sys_errno$LAYOUT, sys_errno$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout sys$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sys"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     int sys_errno;
         * } sys
         * }
         */
        public static final GroupLayout sys$layout() {
            return sys$LAYOUT;
        }

        private static final long sys$OFFSET = $LAYOUT.byteOffset(groupElement("sys"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     int sys_errno;
         * } sys
         * }
         */
        public static final long sys$offset() {
            return sys$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     int sys_errno;
         * } sys
         * }
         */
        public static MemorySegment sys(MemorySegment union) {
            return union.asSlice(sys$OFFSET, sys$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     int sys_errno;
         * } sys
         * }
         */
        public static void sys(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, sys$OFFSET, sys$LAYOUT.byteSize());
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_cas_t cas;
         *         uint64_t offset;
         *     };
         * }
         * }
         */
        public static class internal {

            internal() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                MemoryLayout.unionLayout(
                    ipc_error_cas_t.layout().withName("cas"),
                    ipc_channel_h.C_LONG_LONG.withName("offset")
                ).withName("$anon$77:13")
            ).withName("$anon$76:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final GroupLayout cas$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$77:13"), groupElement("cas"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * ipc_error_cas_t cas
             * }
             */
            public static final GroupLayout cas$layout() {
                return cas$LAYOUT;
            }

            private static final long cas$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$77:13"), groupElement("cas"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * ipc_error_cas_t cas
             * }
             */
            public static final long cas$offset() {
                return cas$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * ipc_error_cas_t cas
             * }
             */
            public static MemorySegment cas(MemorySegment struct) {
                return struct.asSlice(cas$OFFSET, cas$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * ipc_error_cas_t cas
             * }
             */
            public static void cas(MemorySegment struct, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, struct, cas$OFFSET, cas$LAYOUT.byteSize());
            }

            private static final OfLong offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("$anon$77:13"), groupElement("offset"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * uint64_t offset
             * }
             */
            public static final OfLong offset$layout() {
                return offset$LAYOUT;
            }

            private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$77:13"), groupElement("offset"));

            /**
             * Offset for field:
             * {@snippet lang=c :
             * uint64_t offset
             * }
             */
            public static final long offset$offset() {
                return offset$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * uint64_t offset
             * }
             */
            public static long offset(MemorySegment struct) {
                return struct.get(offset$LAYOUT, offset$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * uint64_t offset
             * }
             */
            public static void offset(MemorySegment struct, long fieldValue) {
                struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout internal$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("internal"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_cas_t cas;
         *         uint64_t offset;
         *     };
         * } internal
         * }
         */
        public static final GroupLayout internal$layout() {
            return internal$LAYOUT;
        }

        private static final long internal$OFFSET = $LAYOUT.byteOffset(groupElement("internal"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_cas_t cas;
         *         uint64_t offset;
         *     };
         * } internal
         * }
         */
        public static final long internal$offset() {
            return internal$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_cas_t cas;
         *         uint64_t offset;
         *     };
         * } internal
         * }
         */
        public static MemorySegment internal(MemorySegment union) {
            return union.asSlice(internal$OFFSET, internal$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     union {
         *         ipc_error_cas_t cas;
         *         uint64_t offset;
         *     };
         * } internal
         * }
         */
        public static void internal(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, internal$OFFSET, internal$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout as$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("as"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         union {
     *             ipc_error_size_t size;
     *             ipc_error_capacity_t capacity;
     *         };
     *     } arg;
     *     struct {
     *         int sys_errno;
     *     } sys;
     *     struct {
     *         union {
     *             ipc_error_cas_t cas;
     *             uint64_t offset;
     *         };
     *     } internal;
     * } as
     * }
     */
    public static final GroupLayout as$layout() {
        return as$LAYOUT;
    }

    private static final long as$OFFSET = $LAYOUT.byteOffset(groupElement("as"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         union {
     *             ipc_error_size_t size;
     *             ipc_error_capacity_t capacity;
     *         };
     *     } arg;
     *     struct {
     *         int sys_errno;
     *     } sys;
     *     struct {
     *         union {
     *             ipc_error_cas_t cas;
     *             uint64_t offset;
     *         };
     *     } internal;
     * } as
     * }
     */
    public static final long as$offset() {
        return as$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         union {
     *             ipc_error_size_t size;
     *             ipc_error_capacity_t capacity;
     *         };
     *     } arg;
     *     struct {
     *         int sys_errno;
     *     } sys;
     *     struct {
     *         union {
     *             ipc_error_cas_t cas;
     *             uint64_t offset;
     *         };
     *     } internal;
     * } as
     * }
     */
    public static MemorySegment as(MemorySegment struct) {
        return struct.asSlice(as$OFFSET, as$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         union {
     *             ipc_error_size_t size;
     *             ipc_error_capacity_t capacity;
     *         };
     *     } arg;
     *     struct {
     *         int sys_errno;
     *     } sys;
     *     struct {
     *         union {
     *             ipc_error_cas_t cas;
     *             uint64_t offset;
     *         };
     *     } internal;
     * } as
     * }
     */
    public static void as(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, as$OFFSET, as$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

