// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     size_t limit;
 *     size_t requested_size;
 *     size_t suggested_size;
 * }
 * }
 */
public class ipc_error_size_t {

    ipc_error_size_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_LONG.withName("limit"),
        ipc_channel_h.C_LONG.withName("requested_size"),
        ipc_channel_h.C_LONG.withName("suggested_size")
    ).withName("$anon$48:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong limit$LAYOUT = (OfLong)$LAYOUT.select(groupElement("limit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t limit
     * }
     */
    public static final OfLong limit$layout() {
        return limit$LAYOUT;
    }

    private static final long limit$OFFSET = $LAYOUT.byteOffset(groupElement("limit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t limit
     * }
     */
    public static final long limit$offset() {
        return limit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t limit
     * }
     */
    public static long limit(MemorySegment struct) {
        return struct.get(limit$LAYOUT, limit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t limit
     * }
     */
    public static void limit(MemorySegment struct, long fieldValue) {
        struct.set(limit$LAYOUT, limit$OFFSET, fieldValue);
    }

    private static final OfLong requested_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("requested_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static final OfLong requested_size$layout() {
        return requested_size$LAYOUT;
    }

    private static final long requested_size$OFFSET = $LAYOUT.byteOffset(groupElement("requested_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static final long requested_size$offset() {
        return requested_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static long requested_size(MemorySegment struct) {
        return struct.get(requested_size$LAYOUT, requested_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static void requested_size(MemorySegment struct, long fieldValue) {
        struct.set(requested_size$LAYOUT, requested_size$OFFSET, fieldValue);
    }

    private static final OfLong suggested_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("suggested_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t suggested_size
     * }
     */
    public static final OfLong suggested_size$layout() {
        return suggested_size$LAYOUT;
    }

    private static final long suggested_size$OFFSET = $LAYOUT.byteOffset(groupElement("suggested_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t suggested_size
     * }
     */
    public static final long suggested_size$offset() {
        return suggested_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t suggested_size
     * }
     */
    public static long suggested_size(MemorySegment struct) {
        return struct.get(suggested_size$LAYOUT, suggested_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t suggested_size
     * }
     */
    public static void suggested_size(MemorySegment struct, long fieldValue) {
        struct.set(suggested_size$LAYOUT, suggested_size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

