// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     size_t provided_capacity;
 *     size_t required_capacity;
 * }
 * }
 */
public class ipc_error_capacity_t {

    ipc_error_capacity_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_error_h.C_LONG.withName("provided_capacity"),
        ipc_error_h.C_LONG.withName("required_capacity")
    ).withName("$anon$54:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong provided_capacity$LAYOUT = (OfLong)$LAYOUT.select(groupElement("provided_capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t provided_capacity
     * }
     */
    public static final OfLong provided_capacity$layout() {
        return provided_capacity$LAYOUT;
    }

    private static final long provided_capacity$OFFSET = $LAYOUT.byteOffset(groupElement("provided_capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t provided_capacity
     * }
     */
    public static final long provided_capacity$offset() {
        return provided_capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t provided_capacity
     * }
     */
    public static long provided_capacity(MemorySegment struct) {
        return struct.get(provided_capacity$LAYOUT, provided_capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t provided_capacity
     * }
     */
    public static void provided_capacity(MemorySegment struct, long fieldValue) {
        struct.set(provided_capacity$LAYOUT, provided_capacity$OFFSET, fieldValue);
    }

    private static final OfLong required_capacity$LAYOUT = (OfLong)$LAYOUT.select(groupElement("required_capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t required_capacity
     * }
     */
    public static final OfLong required_capacity$layout() {
        return required_capacity$LAYOUT;
    }

    private static final long required_capacity$OFFSET = $LAYOUT.byteOffset(groupElement("required_capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t required_capacity
     * }
     */
    public static final long required_capacity$offset() {
        return required_capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t required_capacity
     * }
     */
    public static long required_capacity(MemorySegment struct) {
        return struct.get(required_capacity$LAYOUT, required_capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t required_capacity
     * }
     */
    public static void required_capacity(MemorySegment struct, long fieldValue) {
        struct.set(required_capacity$LAYOUT, required_capacity$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

