// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     ipc_cas_target_t target;
 *     uint64_t expected_offset;
 *     uint64_t actual_offset;
 *     uint64_t desired_offset;
 * }
 * }
 */
public class ipc_error_cas_t {

    ipc_error_cas_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_error_h.C_INT.withName("target"),
        MemoryLayout.paddingLayout(4),
        ipc_error_h.C_LONG_LONG.withName("expected_offset"),
        ipc_error_h.C_LONG_LONG.withName("actual_offset"),
        ipc_error_h.C_LONG_LONG.withName("desired_offset")
    ).withName("$anon$41:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt target$LAYOUT = (OfInt)$LAYOUT.select(groupElement("target"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ipc_cas_target_t target
     * }
     */
    public static final OfInt target$layout() {
        return target$LAYOUT;
    }

    private static final long target$OFFSET = $LAYOUT.byteOffset(groupElement("target"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ipc_cas_target_t target
     * }
     */
    public static final long target$offset() {
        return target$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ipc_cas_target_t target
     * }
     */
    public static int target(MemorySegment struct) {
        return struct.get(target$LAYOUT, target$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ipc_cas_target_t target
     * }
     */
    public static void target(MemorySegment struct, int fieldValue) {
        struct.set(target$LAYOUT, target$OFFSET, fieldValue);
    }

    private static final OfLong expected_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("expected_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t expected_offset
     * }
     */
    public static final OfLong expected_offset$layout() {
        return expected_offset$LAYOUT;
    }

    private static final long expected_offset$OFFSET = $LAYOUT.byteOffset(groupElement("expected_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t expected_offset
     * }
     */
    public static final long expected_offset$offset() {
        return expected_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t expected_offset
     * }
     */
    public static long expected_offset(MemorySegment struct) {
        return struct.get(expected_offset$LAYOUT, expected_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t expected_offset
     * }
     */
    public static void expected_offset(MemorySegment struct, long fieldValue) {
        struct.set(expected_offset$LAYOUT, expected_offset$OFFSET, fieldValue);
    }

    private static final OfLong actual_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("actual_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t actual_offset
     * }
     */
    public static final OfLong actual_offset$layout() {
        return actual_offset$LAYOUT;
    }

    private static final long actual_offset$OFFSET = $LAYOUT.byteOffset(groupElement("actual_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t actual_offset
     * }
     */
    public static final long actual_offset$offset() {
        return actual_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t actual_offset
     * }
     */
    public static long actual_offset(MemorySegment struct) {
        return struct.get(actual_offset$LAYOUT, actual_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t actual_offset
     * }
     */
    public static void actual_offset(MemorySegment struct, long fieldValue) {
        struct.set(actual_offset$LAYOUT, actual_offset$OFFSET, fieldValue);
    }

    private static final OfLong desired_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("desired_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t desired_offset
     * }
     */
    public static final OfLong desired_offset$layout() {
        return desired_offset$LAYOUT;
    }

    private static final long desired_offset$OFFSET = $LAYOUT.byteOffset(groupElement("desired_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t desired_offset
     * }
     */
    public static final long desired_offset$offset() {
        return desired_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t desired_offset
     * }
     */
    public static long desired_offset(MemorySegment struct) {
        return struct.get(desired_offset$LAYOUT, desired_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t desired_offset
     * }
     */
    public static void desired_offset(MemorySegment struct, long fieldValue) {
        struct.set(desired_offset$LAYOUT, desired_offset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

