// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IpcChannelDestroyError {
 *     bool _unit;
 * }
 * }
 */
public class IpcChannelDestroyError {

    IpcChannelDestroyError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_BOOL.withName("_unit")
    ).withName("IpcChannelDestroyError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean _unit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("_unit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool _unit
     * }
     */
    public static final OfBoolean _unit$layout() {
        return _unit$LAYOUT;
    }

    private static final long _unit$OFFSET = $LAYOUT.byteOffset(groupElement("_unit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool _unit
     * }
     */
    public static final long _unit$offset() {
        return _unit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool _unit
     * }
     */
    public static boolean _unit(MemorySegment struct) {
        return struct.get(_unit$LAYOUT, _unit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool _unit
     * }
     */
    public static void _unit(MemorySegment struct, boolean fieldValue) {
        struct.set(_unit$LAYOUT, _unit$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

