// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IpcChannelReadError {
 *     uint64_t offset;
 *     struct timespec timeout_used;
 *     int sys_errno;
 * }
 * }
 */
public class IpcChannelReadError {

    IpcChannelReadError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_LONG_LONG.withName("offset"),
        timespec.layout().withName("timeout_used"),
        ipc_channel_h.C_INT.withName("sys_errno"),
        MemoryLayout.paddingLayout(4)
    ).withName("IpcChannelReadError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final OfLong offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static long offset(MemorySegment struct) {
        return struct.get(offset$LAYOUT, offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static void offset(MemorySegment struct, long fieldValue) {
        struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
    }

    private static final GroupLayout timeout_used$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("timeout_used"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct timespec timeout_used
     * }
     */
    public static final GroupLayout timeout_used$layout() {
        return timeout_used$LAYOUT;
    }

    private static final long timeout_used$OFFSET = $LAYOUT.byteOffset(groupElement("timeout_used"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct timespec timeout_used
     * }
     */
    public static final long timeout_used$offset() {
        return timeout_used$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct timespec timeout_used
     * }
     */
    public static MemorySegment timeout_used(MemorySegment struct) {
        return struct.asSlice(timeout_used$OFFSET, timeout_used$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct timespec timeout_used
     * }
     */
    public static void timeout_used(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, timeout_used$OFFSET, timeout_used$LAYOUT.byteSize());
    }

    private static final OfInt sys_errno$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sys_errno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static final OfInt sys_errno$layout() {
        return sys_errno$LAYOUT;
    }

    private static final long sys_errno$OFFSET = $LAYOUT.byteOffset(groupElement("sys_errno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static final long sys_errno$offset() {
        return sys_errno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static int sys_errno(MemorySegment struct) {
        return struct.get(sys_errno$LAYOUT, sys_errno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static void sys_errno(MemorySegment struct, int fieldValue) {
        struct.set(sys_errno$LAYOUT, sys_errno$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

