// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IpcChannelWriteResult {
 *     IpcStatus ipc_status;
 *     union {
 *         unsigned char _u;
 *         IpcChannelWriteResultError error;
 *     };
 * }
 * }
 */
public class IpcChannelWriteResult {

    IpcChannelWriteResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_INT.withName("ipc_status"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            ipc_channel_h.C_CHAR.withName("_u"),
            IpcChannelWriteResultError.layout().withName("error")
        ).withName("$anon$45:1")
    ).withName("IpcChannelWriteResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ipc_status$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ipc_status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * IpcStatus ipc_status
     * }
     */
    public static final OfInt ipc_status$layout() {
        return ipc_status$LAYOUT;
    }

    private static final long ipc_status$OFFSET = $LAYOUT.byteOffset(groupElement("ipc_status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * IpcStatus ipc_status
     * }
     */
    public static final long ipc_status$offset() {
        return ipc_status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * IpcStatus ipc_status
     * }
     */
    public static int ipc_status(MemorySegment struct) {
        return struct.get(ipc_status$LAYOUT, ipc_status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * IpcStatus ipc_status
     * }
     */
    public static void ipc_status(MemorySegment struct, int fieldValue) {
        struct.set(ipc_status$LAYOUT, ipc_status$OFFSET, fieldValue);
    }

    private static final OfByte _u$LAYOUT = (OfByte)$LAYOUT.select(groupElement("$anon$45:1"), groupElement("_u"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char _u
     * }
     */
    public static final OfByte _u$layout() {
        return _u$LAYOUT;
    }

    private static final long _u$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$45:1"), groupElement("_u"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char _u
     * }
     */
    public static final long _u$offset() {
        return _u$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char _u
     * }
     */
    public static byte _u(MemorySegment struct) {
        return struct.get(_u$LAYOUT, _u$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char _u
     * }
     */
    public static void _u(MemorySegment struct, byte fieldValue) {
        struct.set(_u$LAYOUT, _u$OFFSET, fieldValue);
    }

    private static final GroupLayout error$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$45:1"), groupElement("error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * IpcChannelWriteResultError error
     * }
     */
    public static final GroupLayout error$layout() {
        return error$LAYOUT;
    }

    private static final long error$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$45:1"), groupElement("error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * IpcChannelWriteResultError error
     * }
     */
    public static final long error$offset() {
        return error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * IpcChannelWriteResultError error
     * }
     */
    public static MemorySegment error(MemorySegment struct) {
        return struct.asSlice(error$OFFSET, error$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * IpcChannelWriteResultError error
     * }
     */
    public static void error(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, error$OFFSET, error$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

