// Generated by jextract

package jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IpcChannelConnectError {
 *     int sys_errno;
 *     size_t min_size;
 * }
 * }
 */
public class IpcChannelConnectError {

    IpcChannelConnectError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_INT.withName("sys_errno"),
        MemoryLayout.paddingLayout(4),
        ipc_channel_h.C_LONG.withName("min_size")
    ).withName("IpcChannelConnectError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sys_errno$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sys_errno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static final OfInt sys_errno$layout() {
        return sys_errno$LAYOUT;
    }

    private static final long sys_errno$OFFSET = $LAYOUT.byteOffset(groupElement("sys_errno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static final long sys_errno$offset() {
        return sys_errno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static int sys_errno(MemorySegment struct) {
        return struct.get(sys_errno$LAYOUT, sys_errno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int sys_errno
     * }
     */
    public static void sys_errno(MemorySegment struct, int fieldValue) {
        struct.set(sys_errno$LAYOUT, sys_errno$OFFSET, fieldValue);
    }

    private static final OfLong min_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("min_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t min_size
     * }
     */
    public static final OfLong min_size$layout() {
        return min_size$LAYOUT;
    }

    private static final long min_size$OFFSET = $LAYOUT.byteOffset(groupElement("min_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t min_size
     * }
     */
    public static final long min_size$offset() {
        return min_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t min_size
     * }
     */
    public static long min_size(MemorySegment struct) {
        return struct.get(min_size$LAYOUT, min_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t min_size
     * }
     */
    public static void min_size(MemorySegment struct, long fieldValue) {
        struct.set(min_size$LAYOUT, min_size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

