// Generated by jextract

package lib.shm.ipc.jextract.channel;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IpcChannelSkipForceResultError {
 *     const char *detail;
 *     IpcChannelSkipForceError body;
 *     bool hasBody;
 * }
 * }
 */
public class IpcChannelSkipForceResultError {

    IpcChannelSkipForceResultError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_POINTER.withName("detail"),
        IpcChannelSkipForceError.layout().withName("body"),
        ipc_channel_h.C_BOOL.withName("hasBody"),
        MemoryLayout.paddingLayout(6)
    ).withName("IpcChannelSkipForceResultError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout detail$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("detail"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *detail
     * }
     */
    public static final AddressLayout detail$layout() {
        return detail$LAYOUT;
    }

    private static final long detail$OFFSET = $LAYOUT.byteOffset(groupElement("detail"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *detail
     * }
     */
    public static final long detail$offset() {
        return detail$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *detail
     * }
     */
    public static MemorySegment detail(MemorySegment struct) {
        return struct.get(detail$LAYOUT, detail$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *detail
     * }
     */
    public static void detail(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(detail$LAYOUT, detail$OFFSET, fieldValue);
    }

    private static final GroupLayout body$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("body"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * IpcChannelSkipForceError body
     * }
     */
    public static final GroupLayout body$layout() {
        return body$LAYOUT;
    }

    private static final long body$OFFSET = $LAYOUT.byteOffset(groupElement("body"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * IpcChannelSkipForceError body
     * }
     */
    public static final long body$offset() {
        return body$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * IpcChannelSkipForceError body
     * }
     */
    public static MemorySegment body(MemorySegment struct) {
        return struct.asSlice(body$OFFSET, body$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * IpcChannelSkipForceError body
     * }
     */
    public static void body(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, body$OFFSET, body$LAYOUT.byteSize());
    }

    private static final OfBoolean hasBody$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("hasBody"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool hasBody
     * }
     */
    public static final OfBoolean hasBody$layout() {
        return hasBody$LAYOUT;
    }

    private static final long hasBody$OFFSET = $LAYOUT.byteOffset(groupElement("hasBody"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool hasBody
     * }
     */
    public static final long hasBody$offset() {
        return hasBody$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool hasBody
     * }
     */
    public static boolean hasBody(MemorySegment struct) {
        return struct.get(hasBody$LAYOUT, hasBody$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool hasBody
     * }
     */
    public static void hasBody(MemorySegment struct, boolean fieldValue) {
        struct.set(hasBody$LAYOUT, hasBody$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

