// Generated by jextract

package lib.shm.ipc.jextract.channel;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IpcChannelWriteError {
 *     uint64_t offset;
 *     size_t requested_size;
 *     size_t available_contiguous;
 *     size_t buffer_size;
 * }
 * }
 */
public class IpcChannelWriteError {

    IpcChannelWriteError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ipc_channel_h.C_LONG_LONG.withName("offset"),
        ipc_channel_h.C_LONG.withName("requested_size"),
        ipc_channel_h.C_LONG.withName("available_contiguous"),
        ipc_channel_h.C_LONG.withName("buffer_size")
    ).withName("IpcChannelWriteError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final OfLong offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static long offset(MemorySegment struct) {
        return struct.get(offset$LAYOUT, offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t offset
     * }
     */
    public static void offset(MemorySegment struct, long fieldValue) {
        struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
    }

    private static final OfLong requested_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("requested_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static final OfLong requested_size$layout() {
        return requested_size$LAYOUT;
    }

    private static final long requested_size$OFFSET = $LAYOUT.byteOffset(groupElement("requested_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static final long requested_size$offset() {
        return requested_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static long requested_size(MemorySegment struct) {
        return struct.get(requested_size$LAYOUT, requested_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t requested_size
     * }
     */
    public static void requested_size(MemorySegment struct, long fieldValue) {
        struct.set(requested_size$LAYOUT, requested_size$OFFSET, fieldValue);
    }

    private static final OfLong available_contiguous$LAYOUT = (OfLong)$LAYOUT.select(groupElement("available_contiguous"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t available_contiguous
     * }
     */
    public static final OfLong available_contiguous$layout() {
        return available_contiguous$LAYOUT;
    }

    private static final long available_contiguous$OFFSET = $LAYOUT.byteOffset(groupElement("available_contiguous"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t available_contiguous
     * }
     */
    public static final long available_contiguous$offset() {
        return available_contiguous$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t available_contiguous
     * }
     */
    public static long available_contiguous(MemorySegment struct) {
        return struct.get(available_contiguous$LAYOUT, available_contiguous$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t available_contiguous
     * }
     */
    public static void available_contiguous(MemorySegment struct, long fieldValue) {
        struct.set(available_contiguous$LAYOUT, available_contiguous$OFFSET, fieldValue);
    }

    private static final OfLong buffer_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("buffer_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t buffer_size
     * }
     */
    public static final OfLong buffer_size$layout() {
        return buffer_size$LAYOUT;
    }

    private static final long buffer_size$OFFSET = $LAYOUT.byteOffset(groupElement("buffer_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t buffer_size
     * }
     */
    public static final long buffer_size$offset() {
        return buffer_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t buffer_size
     * }
     */
    public static long buffer_size(MemorySegment struct) {
        return struct.get(buffer_size$LAYOUT, buffer_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t buffer_size
     * }
     */
    public static void buffer_size(MemorySegment struct, long fieldValue) {
        struct.set(buffer_size$LAYOUT, buffer_size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

