/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_shm_ipc_jni_IpcChannel */

#ifndef _Included_lib_shm_ipc_jni_IpcChannel
#define _Included_lib_shm_ipc_jni_IpcChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    create
 * Signature: (Ljava/lang/String;J)Llib/shm/ipc/result/IpcChannelResult;
 */
JNIEXPORT jobject JNICALL Java_lib_shm_ipc_jni_IpcChannel_create
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    attach
 * Signature: (Ljava/lang/String;J)Llib/shm/ipc/result/IpcChannelResult;
 */
JNIEXPORT jobject JNICALL Java_lib_shm_ipc_jni_IpcChannel_attach
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    suggestSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_shm_ipc_jni_IpcChannel_suggestSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    write
 * Signature: ([B)Llib/shm/ipc/result/IpcBooleanResult;
 */
JNIEXPORT jobject JNICALL Java_lib_shm_ipc_jni_IpcChannel_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    tryRead
 * Signature: ()Llib/shm/ipc/result/IpcBytesResult;
 */
JNIEXPORT jobject JNICALL Java_lib_shm_ipc_jni_IpcChannel_tryRead
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
