/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_shm_ipc_jni_IpcChannel */

#ifndef _Included_lib_shm_ipc_jni_IpcChannel
#define _Included_lib_shm_ipc_jni_IpcChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    write
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_lib_shm_ipc_jni_IpcChannel_write(JNIEnv *, jobject,
                                                             jbyteArray);

/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    read
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_lib_shm_ipc_jni_IpcChannel_read(JNIEnv *,
                                                                  jobject);

/*
 * Class:     lib_shm_ipc_jni_IpcChannel
 * Method:    init
 * Signature: (Ljava/lang/String;JZ)J
 */
JNIEXPORT jlong JNICALL Java_lib_shm_ipc_jni_IpcChannel_init(JNIEnv *, jobject,
                                                             jstring, jlong,
                                                             jboolean);

#ifdef __cplusplus
}
#endif
#endif
